#ifndef OVE_VGA_H
#define OVE_VGA_H
/*
**  $Source: PRG:VFM/Include/visualstuff/ove_vga.h,v $
**  $Revision: 38.4 $
**  $Date: 1995/10/01 00:26:38 $
**  $Locker:  $
**  $Author: floh $
**
**  Definitionen für VGA-Gfx-Engine.
**
**  (C) Copyright 1994 by A.Weissflog
*/
#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif

#ifndef VISUALSTUFF_SPANGINE_H
#include "visualstuff/spangine.h"
#endif

#ifndef OV_ENGINE_H
#include "visualstuff/ov_engine.h"
#endif

/*-----------------------------------------------------------------*/
#endif

